language: node_js
sudo: false
dist: trusty
node_js: stable
addons:
  firefox: latest
  chrome: stable
cache:
  directories:
  - node_modules
before_script:
- npm install -g web-component-tester
script:
- xvfb-run ./node_modules/.bin/wct --configFile wct.conf.json