language: node_js
sudo: false
dist: trusty
node_js: stable
addons:
  firefox: latest
  chrome: stable
cache:
  directories:
  - node_modules
before_script:
- npm i
- npm install polymer-cli
script:
- xvfb-run ./node_modules/.bin/polymer test